test_suites:
    - name: publish
      script_path: /root/okta/okta-management-openapi-spec/scripts
      sort_order: '0'
      timeout: '10'
      script_name: publish
      criteria: MERGE
      queue_name: small
