version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9

jobs:
  snyk-scan:
    docker:
      - image: cimg/python:3.10
    steps:
      - attach_workspace: # Allows for sharing of build-workspace (containing downloaded dependencies) (optional)
          at: ~/project # This is the working directory for CCI containers, change if necessary
      - checkout # Might not need this if you have "persist_to_workspace" and "attach_workspace"
      - run: |   # Might not need this if you have "persist_to_workspace" and "attach_workspace"
          pip install -r requirements.txt
      - platform-helpers-general/step-load-dependencies
      - platform-helpers-general/step-run-snyk-monitor:
          scan-all-projects: true
          skip-unresolved: false
          run-on-non-main: true
workflows:
  # See OKTA-624828 
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          context:
            - static-analysis
      - snyk-scan:
          name: execute-snyk
          context:
            - static-analysis
